export const LOGIN_SET_VALUE_BY_KEY = "LOGIN_SET_VALUE_BY_KEY";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const ON_FAKEENTER = "ON_FAKEENTER";
export const CLEAN_FORM = "CLEAN_FORM";
