export const REGISTRATION_SET_VALUE_BY_KEY = "REGISTRATION_SET_VALUE_BY_KEY";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";
export const REGISTRATION_CLEAN_FORM = "REGISTRATION_CLEAN_FORM";
export const REGISTRATION_SET_VALIDATION_MESSAGE =
  "REGISTRATION_SET_VALIDATION_MESSAGE";
