export const RECOVERY_SET_VALUE_BY_KEY = "RECOVERY_SET_VALUE_BY_KEY";
export const RECOVERY_CLEAN_FORM = "RECOVERY_CLEAN_FORM";
export const RECOVERY_SET_VALIDATION_MESSAGE =
  "RECOVERY_SET_VALIDATION_MESSAGE";
